### ISSUE TITLE
Cannot find module "sharp" at Vercel Deployment when using latest version

### ISSUE THREAD

**Issue by mich040m** [payloadcms/next-payload#72]
So I did a yolo update all dependencies on my project and started getting that error, downgrading each dep one by one until I found the culprit. 

When using `"@payloadcms/next-payload": "^0.0.37",` I get the error mentioned in title when deploying app on Vercel, but not on local. I downgraded to `"@payloadcms/next-payload": "^0.0.33",`. And it got fixed. 

package.json:

```
"dependencies": {
    "@aws-sdk/client-s3": "^3.412.0",
    "@aws-sdk/lib-storage": "^3.412.0",
    "@aws-sdk/signature-v4-crt": "^3.412.0",
    "@heroicons/react": "^2.0.18",
    "@hookform/resolvers": "^3.3.1",
    "@next/eslint-plugin-next": "^13.4.19",
    "@payloadcms/next-payload": "^0.0.33",
    "@payloadcms/plugin-cloud-storage": "^1.0.19",
    "@payloadcms/plugin-seo": "^1.0.14-canary.0",
    "@radix-ui/react-accordion": "^1.1.2",
    "@radix-ui/react-alert-dialog": "^1.0.4",
    "@radix-ui/react-dialog": "^1.0.4",
    "@radix-ui/react-dropdown-menu": "^2.0.5",
    "@radix-ui/react-label": "^2.0.2",
    "@radix-ui/react-navigation-menu": "^1.1.3",
    "@radix-ui/react-slot": "^1.0.2",
    "@radix-ui/react-switch": "^1.0.3",
    "@radix-ui/react-toast": "^1.1.4",
    "@types/node": "20.6.0",
    "@types/react": "18.2.21",
    "@types/react-dom": "18.2.7",
    "autoprefixer": "10.4.15",
    "class-variance-authority": "^0.7.0",
    "client-only": "^0.0.1",
    "clsx": "^2.0.0",
    "cookie": "^0.5.0",
    "dotenv": "^16.3.1",
    "eslint": "8.49.0",
    "eslint-config-next": "13.4.19",
    "framer-motion": "^10.16.4",
    "lucide-react": "^0.277.0",
    "next": "13.5.1",
    "next-intl": "^3.0.0-beta.9",
    "next-nprogress-bar": "^2.1.2",
    "payload": "^1.15.6",
    "postcss": "8.4.29",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-hook-form": "^7.46.1",
    "swr": "^2.2.2",
    "tailwind-merge": "^1.14.0",
    "tailwindcss": "3.3.3",
    "tailwindcss-animate": "^1.0.7",
    "typescript": "5.2.2",
    "zod": "^3.22.2"
  },
  "devDependencies": {
    "@types/cookie": "^0.5.1",
    "@types/gtag.js": "^0.0.12",
    "@typescript-eslint/eslint-plugin": "^6.7.0",
    "@typescript-eslint/parser": "^6.7.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-plugin-prettier": "^5.0.0",
    "prettier": "^3.0.3"
  }
```

Error from Vercel platform:

```
` …erations/local/index.js',
    '/var/task/node_modules/payload/dist/payload.js',
    '/var/task/.next/server/app/[locale]/page.js',
    '/var/task/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/___next_launcher.cjs'
  ]
}
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '3226682145'
}
Error: Cannot find module 'sharp'
Require stack:
- /var/task/node_modules/payload/dist/uploads/generateFileData.js
- /var/task/node_modules/payload/dist/collections/operations/create.js
- /var/task/node_modules/payload/dist/collections/operations/local/create.js
- /var/task/node_modules/payload/dist/collections/operations/local/index.js
- /var/task/node_modules/payload/dist/payload.js
- /var/task/.next/server/app/[locale]/page.js
- /var/task/node_modules/next/dist/server/require.js
- /var/task/node_modules/next/dist/server/next-server.js
- /var/task/___next_launcher.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at /var/task/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at e.<computed>._module.Module._load (/var/task/___vc/__launcher.js:15:1965)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at mod.require (/var/task/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/var/task/node_modules/payload/dist/uploads/generateFileData.js:11:33)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/payload/dist/uploads/generateFileData.js',
    '/var/task/node_modules/payload/dist/collections/operations/create.js',
    '/var/task/node_modules/payload/dist/collections/operations/local/create.js',
    '/var/task/node_modules/payload/dist/collections/operations/local/index.js',
    '/var/task/node_modules/payload/dist/payload.js',
    '/var/task/.next/server/app/[locale]/page.js',
    '/var/task/node_modules/next/dist/server/require.js',
    '/var/task/node_modules/next/dist/server/next-server.js',
    '/var/task/___next_launcher.cjs'
  ]
}
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '3226682145'
}
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '3226682145',
  page: '/en'
}
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '3226682145',
  page: '/en'
}
RequestId: 412d7d4d-d200-4bd2-8882-8ae8777b92be Error: Runtime exited with error: exit status 1
Runtime.ExitError `
```

**Comment by Utzel-Butzel** [comment]
I solved it with a quick hack in my `next.config.js` which removes sharp from getting ignored in the config.

```js
async function outputConfig() {
  const config = await nextConfig;

  const index = result.experimental.outputFileTracingIgnores.indexOf(
    "node_modules/sharp/**/*"
  );

  config.experimental.outputFileTracingIgnores.splice(index, 1);

  return config;
}

module.exports = outputConfig;
```

**Comment by Shmookoff** [comment]
Having the same issue. Suggested workaround from previous post didn't work for me.

**Comment by joschan21** [comment]
Same issue here

**Comment by thebiltheory** [comment]
+1 It's on production. Is there any way we can make this a P0?

**Comment by joschan21** [comment]
> +1 It's on production. Is there any way we can make this a P0?

for me its just in prod too, locally everything besides the next config warnings works fine

**Comment by thebiltheory** [comment]
cc @denolfe We're really stuck here. Any suggestion?

**Comment by jmikrut** [comment]
Hey everyone - we will get you answers here today. Give us a bit and we will get back to you shortly!

**Comment by jmikrut** [comment]
OK so we dug into this issue and we have not been able to reproduce, running on the latest NextJS version and latest Payload version. But I can provide some background context here in hopes that the solution / steps to reproduce will reveal itself, and then we can fix accordingly.

Basically, we detect if your config requires Sharp to be present in your serverless functions, and if it is not required, then we explicitly ignore it from the serverless function output (serverless functions should be as small as possible, and Sharp is a big package). Typically because the `next/image` package is so helpful out of the box, we figure this alleviates a lot of what Sharp would be used for in the first place. 

Here is how we detect if your config requires Sharp:
https://github.com/payloadcms/next-payload/blob/main/withPayloadPlugin.js#L30

Notice how if you have an upload-enabled collection that leverages `upload.imageSizes || upload.resizeOptions || upload.formatOptions` we will NOT exclude Sharp. 

But if you don't have any of those used, we will indeed exclude Sharp from the production build.

So, question for everyone in this thread - do you have any collection configs that leverage any of these options? And if not, are you using Sharp somewhere else by chance? 

Last note - if anyone could provide a reproducible example, that will help us as right now we can't reproduce :(

**Comment by thebiltheory** [comment]
@jmikrut I'll check if sharp is used somewhere else.

Has there been any breaking changes in the way payload handles uploads? I implemented payload collections a few months back. 

This is the first line of the error stack.

```
Error: Cannot find module 'sharp'
Require stack:
- /var/task/node_modules/payload/dist/uploads/generateFileData.js
```

I'll update this with my findings.

**Comment by thebiltheory** [comment]
I downgraded to `"@payloadcms/next-payload": "^0.0.33",` like @mich040m suggested.
I am currently short on investigation time. But I'll try to get back when It's time to upgrade.

**Comment by credli** [comment]
This still doesn't work for me, here is what I tried:

- I downgraded to "@payloadcms/next-payload": "^0.0.33", redployed my app, still I get the same error `module not found`. All my API routes that use payload will complain about not being able to find `sharp`. 

- I even tried installing sharp through npm, calls to me API now will report this error:

> Error: 
> Something went wrong installing the "sharp" module
> 
> node-loader:
> Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory

- Also tried the https://github.com/payloadcms/next-payload/issues/72#issuecomment-1732695431 fix but nothing worked. 

- I moved away from Local API to REST, thinking that payload was unable to load a serverless function, that didn't solve the problem.

Can anyone provide me an insight as to why is sharp getting invoked when my API routes reference the payload client? Is there a way to force sharp getting packaged as part of the payloadcms bundle?

Appreciate your feedback, at this point my website has stopped working and I regret updating.

**Comment by JarrodMFlesch** [comment]
@credli Does this happen for you on the latest version? It is based off of 2.0, so you will have to make some changes, but I am unable to replicate this locally or on Vercel.
